const products = [
    {
        _id: '1',
        name: 'Peach and Gold Silk Lehenga',
        image: '/images/lehnga_1.jpeg',
        description: 'Lehenga is a three-piece ensemble consists of the actual lehenga, a long ankle-length skirt, a well-fitted blouse top known as the choli, and a scarf to drape around the outfit, known as the dupatta',
        brand: 'AVIRA',
        category: 'Women',
        price: 15000,
        countInStock: 5,
        rating: 4.2,
        numReviews: 5,
    },
    {
        _id: '2',
        name: 'Bold Pink and silver work Lehenga',
        image: '/images/lehnga_2.jpeg',
        description: 'Lehenga is a three-piece ensemble consists of the actual lehenga, a long ankle-length skirt, a well-fitted blouse top known as the choli, and a scarf to drape around the outfit, known as the dupatta',
        brand: 'AVIRA',
        category: 'Women',
        price: 20000,
        countInStock: 2,
        rating: 3.2,
        numReviews: 2,
    },
    {
        _id: '3',
        name: 'Light Green Lehenga',
        image: '/images/lehnga_3.jpeg',
        description: 'Lehenga is a three-piece ensemble consists of the actual lehenga, a long ankle-length skirt, a well-fitted blouse top known as the choli, and a scarf to drape around the outfit, known as the dupatta',
        brand: 'AVIRA',
        category: 'Women',
        price: 11000,
        countInStock: 8,
        rating: 3.2,
        numReviews: 9,
    },
    {
        _id: '4',
        name: 'White Lehenga',
        image: '/images/lehnga_4.jpeg',
        description: 'Lehenga is a three-piece ensemble consists of the actual lehenga, a long ankle-length skirt, a well-fitted blouse top known as the choli, and a scarf to drape around the outfit, known as the dupatta',
        brand: 'AVIRA',
        category: 'Women',
        price: 30000,
        countInStock: 0,
        rating: 4,
        numReviews: 2,
    },
    {
        _id: '5',
        name: 'Dark Red Lehenga',
        image: '/images/lehnga_5.jpeg',
        description: 'Lehenga is a three-piece ensemble consists of the actual lehenga, a long ankle-length skirt, a well-fitted blouse top known as the choli, and a scarf to drape around the outfit, known as the dupatta',
        brand: 'AVIRA',
        category: 'Women',
        price: 21000,
        countInStock: 9,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: '6',
        name: 'Sky Blue Lehenga',
        image: '/images/lehnga_6.jpeg',
        description: 'Lehenga is a three-piece ensemble consists of the actual lehenga, a long ankle-length skirt, a well-fitted blouse top known as the choli, and a scarf to drape around the outfit, known as the dupatta',
        brand: 'AVIRA',
        category: 'Women',
        price: 10000,
        countInStock: 5,
        rating: 3.5,
        numReviews: 0,
    },
    {
        _id: '7',
        name: ' Gold Silk Lehenga',
        image: '/images/lehnga_7.jpeg',
        description: 'Lehenga is a three-piece ensemble consists of the actual lehenga, a long ankle-length skirt, a well-fitted blouse top known as the choli, and a scarf to drape around the outfit, known as the dupatta',
        brand: 'AVIRA',
        category: 'Women',
        price: 18000,
        countInStock: 3,
        rating: 4.4,
        numReviews: 6,
    },
    {
        _id: '8',
        name: 'Tale Lehenga',
        image: '/images/lehnga_8.jpeg',
        description: 'Lehenga is a three-piece ensemble consists of the actual lehenga, a long ankle-length skirt, a well-fitted blouse top known as the choli, and a scarf to drape around the outfit, known as the dupatta',
        brand: 'AVIRA',
        category: 'Women',
        price: 30000,
        countInStock: 1,
        rating: 4.8,
        numReviews: 45,
    
    },
];

export default products;